### ISSUE TITLE
Can not logon to GS1200-8 - but GS1200-5-POE works fine

### ISSUE THREAD

**Issue by guitarddns** [firepinn/ha-zyxel-poe#1]
I have 2 switch - on GS1200-8 (not a POE) and a GS1200-5-POE - the GS1200-5-POE works fine from integration - but GS1200-8 never even manage to logon - looking in debug log - it seem like another is logon to the switch - and that is not the case - so is this a knowen issue or is it because the plugin only works with a POE definde switch 
Thanks in advance

John

**Comment by firepinn** [comment]
Sorry for the very late reply. I only have the GS1200-5-POE to test with. What exactly are you trying to control on the non-POE version of the GS1200-8?

**Comment by segator** [comment]
for the GS1200-8HP v2

we need to send this.

        data = {
            "g_port_state": 221,
            "g_port_flwcl": 0,
            "g_port_poe": bool_list_to_int(switches),
            "g_port_speed0": 0,
            "g_port_speed1":0,
            "g_port_speed2":0,
            "g_port_speed3":0,
            "g_port_speed4":0,
            "g_port_speed5":0,
            "g_port_speed6":0,
            "g_port_speed7":0
        }
        
       can you adapt the plugin to support both?

**Comment by firepinn** [comment]
Should be fixed by https://github.com/firepinn/ha-zyxel-poe/pull/2
